apiVersion: v1
kind: Service
metadata:
  name: nii-redis
  namespace: nii
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: nii
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: nii
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP