apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nii-qdrant-data
  namespace: nii
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: nii
    app.kubernetes.io/component: vector-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi