# strimzi-operator-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 1.0.0
    helm:
      valuesObject:
        watchAnyNamespace: false
        watchNamespaces:
          - nii-infrastructure
        operationTimeoutMs: 600000
        extraEnvs:
          - name: STRIMZI_KUBERNETES_VERSION
            value: "major=1, minor=30"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
  destination:
    server: https://kubernetes.default.svc
    namespace: nii-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true