apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: telemetry-events
  labels:
    strimzi.io/cluster: nii-kafka
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: incidents
  labels:
    strimzi.io/cluster: nii-kafka
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: alerts
  labels:
    strimzi.io/cluster: nii-kafka
spec:
  partitions: 2
  replicas: 1