apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-cluster-broker-pool
  namespace: nii
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        storageClass: local-path  # use your actual StorageClass name
  resources:
    requests:
      memory: 768Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1000m
  jvmOptions:
    "-Xms": "512m"
    "-Xmx": "768m"