apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: nii-infrastructure
  labels:
    strimzi.io/cluster: nii-kafka-cluster
    app.kubernetes.io/part-of: network-incident-intelligence
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim   # Simplified matching your working Postgres model
    size: 10Gi
    class: local-path
    deleteClaim: false       # Crucial: Protects your data logs during restarts
  nodeSelector:
    workload-type: heavy     # Pins Kafka to the exact same high-capacity server node as Postgres
  resources:
    requests:
      cpu: "500m"            # Elevated to prevent crypto handshake stalling
      memory: "1Gi"          # Reduced slightly so it easily slots into your 4GB node next to Postgres
    limits:
      cpu: "1.5"
      memory: "1.5Gi"