apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: network-alerts
  namespace: nii-kafka
  labels:
    strimzi.io/cluster: nii-kafka-cluster
    app.kubernetes.io/part-of: network-incident-intelligence
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
    segment.bytes: "107374182"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: processed-incidents
  namespace: nii-kafka
  labels:
    strimzi.io/cluster: nii-kafka-cluster
    app.kubernetes.io/part-of: network-incident-intelligence
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
    segment.bytes: "107374182"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: alerts-dead-letter
  namespace: nii-kafka
  labels:
    strimzi.io/cluster: nii-kafka-cluster
    app.kubernetes.io/part-of: network-incident-intelligence
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: "2592000000"