apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: nii-kafka-cluster
spec:
  replicas: 1
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 10Gi
    class: local-path