apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-kafka-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: strimzi-kafka-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator:0.1.0
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh