apiVersion: v1
kind: Secret
metadata:
  name: nii-postgresql-credentials
  namespace: nii
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: nii
    app.kubernetes.io/component: database
type: Opaque
stringData:
  postgres-password: "Ch4ng3M3N0w!Secure2025"
  incident-db-password: "Inc1d3nt@Db.Secure.2025"

  # These are kept for applications/tools that need connection strings.
  # Do not use localhost from another Kubernetes Pod.
  incident-db-connection-string: "postgresql://incident_db:Inc1d3nt%40Db.Secure.2025@nii-postgresql.nii.svc.cluster.local:5432/incident_db"

  postgres-admin-connection-string: "postgresql://postgres:Ch4ng3M3N0w%21Secure2025@nii-postgresql.nii.svc.cluster.local:5432/postgres"
