apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: nii-infrastructure
type: Opaque
stringData:
  POSTGRES_DB: incident_db
  POSTGRES_USER: incident_user
  POSTGRES_PASSWORD: changeme123